#!/usr/bin/env bun

/**
 * Help Content Manager
 *
 * This script helps manage help content by:
 * - Listing all available help topics
 * - Validating help content
 * - Generating help content index
 * - Clearing cache for development
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import {
  getAllHelpContent,
  getHelpCategories,
} from '../src/lib/help-content-loader'

const helpDir = join(process.cwd(), 'help')

function listHelpTopics() {
  console.log('📚 Available Help Topics:\n')

  try {
    const files = readdirSync(helpDir).filter(file => file.endsWith('.md'))

    if (files.length === 0) {
      console.log('No help topics found in the help directory.')
      return
    }

    const content = getAllHelpContent()
    const categories = getHelpCategories()

    console.log(`Total topics: ${files.length}`)
    console.log(`Categories: ${categories.join(', ')}\n`)

    // Group by category
    categories.forEach(category => {
      console.log(`## ${category}`)
      const categoryContent = content.filter(item => item.category === category)

      categoryContent.forEach(item => {
        const filePath = join(helpDir, `${item.id}.md`)
        const stats = readFileSync(filePath, 'utf-8')
        const lineCount = stats.split('\n').length
        const wordCount = stats.split(/\s+/).length

        console.log(`  • ${item.title} (${item.id})`)
        console.log(`    📄 ${lineCount} lines, ${wordCount} words`)
      })
      console.log()
    })

    // List files without metadata
    const contentIds = new Set(content.map(item => item.id))
    const orphanFiles = files.filter(file => {
      const id = file.replace('.md', '')
      return !contentIds.has(id)
    })

    if (orphanFiles.length > 0) {
      console.log('⚠️  Files without metadata:')
      orphanFiles.forEach(file => {
        console.log(`  • ${file}`)
      })
      console.log()
    }
  } catch (error) {
    console.error('Error listing help topics:', error)
  }
}

function validateHelpContent() {
  console.log('🔍 Validating Help Content:\n')

  try {
    const content = getAllHelpContent()
    let hasErrors = false

    content.forEach(item => {
      console.log(`Checking: ${item.title} (${item.id})`)

      // Check for required fields
      if (!item.title) {
        console.log(`  ❌ Missing title`)
        hasErrors = true
      }

      if (!item.content) {
        console.log(`  ❌ Missing content`)
        hasErrors = true
      }

      if (!item.category) {
        console.log(`  ⚠️  Missing category`)
      }

      // Check content length
      if (item.content.length < 50) {
        console.log(
          `  ⚠️  Content seems too short (${item.content.length} chars)`
        )
      }

      // Check for markdown headers
      if (!item.content.includes('#')) {
        console.log(`  ⚠️  No markdown headers found`)
      }

      console.log(`  ✅ Valid`)
    })

    if (!hasErrors) {
      console.log('\n🎉 All help content is valid!')
    } else {
      console.log('\n❌ Some help content has errors. Please fix them.')
    }
  } catch (error) {
    console.error('Error validating help content:', error)
  }
}

function generateHelpIndex() {
  console.log('📋 Generating Help Content Index:\n')

  try {
    const content = getAllHelpContent()
    const categories = getHelpCategories()

    const indexContent = `# Help Content Index

This file is automatically generated. Do not edit manually.

## Overview

- **Total Topics**: ${content.length}
- **Categories**: ${categories.length}
- **Last Updated**: ${new Date().toISOString()}

## Categories

${categories
  .map(category => {
    const categoryContent = content.filter(item => item.category === category)
    return `### ${category} (${categoryContent.length} topics)

${categoryContent.map(item => `- **${item.title}** (\`${item.id}\`)`).join('\n')}`
  })
  .join('\n\n')}

## All Topics

${content.map(item => `- **${item.title}** (\`${item.id}\`) - ${item.category || 'Uncategorized'}`).join('\n')}

## Usage

To use help content in your components:

\`\`\`tsx
import { HelpIcon } from '@/components/help-icon'

<HelpIcon helpId="${content[0]?.id || 'example'}" />
\`\`\`

To add new help content:

1. Create a new markdown file in the \`help/\` directory
2. Add metadata to \`src/lib/help-content-loader.ts\`
3. Run \`bun scripts/help-content-manager.ts validate\` to check
`

    const indexPath = join(process.cwd(), 'help', 'README.md')
    writeFileSync(indexPath, indexContent)

    console.log(`✅ Help index generated: ${indexPath}`)
    console.log(
      `📊 ${content.length} topics indexed across ${categories.length} categories`
    )
  } catch (error) {
    console.error('Error generating help index:', error)
  }
}

function clearCache() {
  console.log('🗑️  Help content is now loaded at build time.')
  console.log('✅ No cache to clear - content is statically imported')
}

function showUsage() {
  console.log(`
Help Content Manager

Usage: bun scripts/help-content-manager.ts <command>

Commands:
  list      List all available help topics
  validate  Validate help content for errors
  index     Generate help content index
  clear     Clear help content cache
  help      Show this help message

Examples:
  bun scripts/help-content-manager.ts list
  bun scripts/help-content-manager.ts validate
  bun scripts/help-content-manager.ts index
`)
}

// Main execution
const command = process.argv[2] || 'help'

switch (command) {
  case 'list':
    listHelpTopics()
    break
  case 'validate':
    validateHelpContent()
    break
  case 'index':
    generateHelpIndex()
    break
  case 'clear':
    clearCache()
    break
  case 'help':
  default:
    showUsage()
    break
}
