export const toolIds = {
  people: 'people',
  initiatives: 'initiatives',
  tasks: 'tasks',
  teams: 'teams',
  currentUser: 'currentUser',
  github: 'github',
  jira: 'jira',
  dateTime: 'dateTime',
  personLookup: 'personLookup',
  teamLookup: 'teamLookup',
  jobRoleLookup: 'jobRoleLookup',
  feedback: 'feedback',
  createOneOnOneAction: 'createOneOnOneAction',
  createPersonAction: 'createPersonAction',
} as const
