import { PageContainer } from '@/components/ui/page-container'
import { PageHeader } from '@/components/ui/page-header'
import { PageContent } from '@/components/ui/page-content'
import { PageSection } from '@/components/ui/page-section'
import { SectionHeader } from '@/components/ui/section-header'
import { getCurrentUser } from '@/lib/auth-utils'
import { getExceptions } from '@/lib/actions/exceptions'
import { ExceptionsList } from '@/components/exceptions/exceptions-list'
import { AlertTriangle } from 'lucide-react'

export default async function ExceptionsPage() {
  const user = await getCurrentUser()

  if (!user.managerOSOrganizationId) {
    return <div>User must belong to an organization to view exceptions</div>
  }

  const exceptions = await getExceptions()

  return (
    <PageContainer>
      <PageHeader
        title='Exceptions'
        subtitle='View and manage exceptions generated by tolerance rules.'
      />

      <PageContent>
        <PageSection
          header={
            <SectionHeader
              icon={AlertTriangle}
              title='Active Exceptions'
              description='Exceptions are generated when tolerance rules detect that thresholds have been exceeded. You can acknowledge, ignore, or resolve exceptions.'
            />
          }
        >
          <ExceptionsList exceptions={exceptions} />
        </PageSection>
      </PageContent>
    </PageContainer>
  )
}
