/**
 * Auto-generated help content: Direct Reports
 *
 * This file is automatically generated from people-teams/direct-reports.md.
 * Do not edit this file manually. Instead, edit the markdown file and run:
 *
 *   bun run help:generate
 *
 * Generated on: 2025-10-22T08:38:41.560Z
 */

export interface HelpContent {
  id: string
  title: string
  content: string
  category?: string
}

export const helpContent: HelpContent = {
  id: 'direct-reports',
  title: 'Direct Reports',
  category: 'People & Teams',
  content: `# Direct Reports

Direct reports are team members who report directly to you. This section provides:

## Overview

- **Team size** and composition
- **Individual performance** indicators
- **Quick access** to team member profiles

## Management Tools

- **One-on-one scheduling** and tracking
- **Performance feedback** collection
- **Goal setting** and progress monitoring
- **Task assignment** and follow-up

## Key Metrics

- **Team productivity** indicators
- **Engagement levels** and satisfaction
- **Development progress** and growth areas

Use this section to stay connected with your team and ensure their success.
`,
}
