/**
 * Auto-generated help content: Initiatives
 *
 * This file is automatically generated from tasks-projects/initiatives.md.
 * Do not edit this file manually. Instead, edit the markdown file and run:
 *
 *   bun run help:generate
 *
 * Generated on: 2025-10-18T20:03:08.388Z
 */

export interface HelpContent {
  id: string
  title: string
  content: string
  category?: string
}

export const helpContent: HelpContent = {
  id: 'initiatives',
  title: 'Initiatives',
  category: 'Tasks & Projects',
  content: `# Initiatives

Initiatives are strategic projects or programs that drive organizational goals forward. They help you:

## What are Initiatives?

- **Strategic projects** with clear objectives
- **Cross-functional work** involving multiple team members
- **Goal-oriented activities** with measurable outcomes

## Key Components

### Objectives

- **Clear, measurable goals** for the initiative
- **Success criteria** and key results
- **Timeline and milestones** for tracking progress

### Tasks

- **Actionable items** that contribute to the initiative
- **Assigned responsibilities** and ownership
- **Progress tracking** and status updates

### Check-ins

- **Regular progress reviews** and updates
- **Stakeholder communication** and alignment
- **Course corrections** and adjustments

## Best Practices

- **Define clear success metrics** before starting
- **Assign clear ownership** for each component
- **Schedule regular check-ins** to maintain momentum
- **Document lessons learned** for future initiatives
`,
}
