/**
 * Auto-generated help content: People
 *
 * This file is automatically generated from people-teams/people.md.
 * Do not edit this file manually. Instead, edit the markdown file and run:
 *
 *   bun run help:generate
 *
 * Generated on: 2025-10-18T20:03:08.387Z
 */

export interface HelpContent {
  id: string
  title: string
  content: string
  category?: string
}

export const helpContent: HelpContent = {
  id: 'people',
  title: 'People',
  category: 'People & Teams',
  content: `# People

The People page is your central hub for managing all team members in your organization. This comprehensive view provides tools for viewing, filtering, and managing people across your organization.

## Overview

The People page displays all members of your organization in a searchable, filterable table format. You can:

- **View all team members** in your organization
- **Filter and search** people by name, role, team, or status
- **Access individual profiles** for detailed information
- **Manage people** (if you're an admin)

## Key Features

### People Table

- **Name and contact information** for each person
- **Role and team assignments**
- **Status indicators** (active, inactive, etc.)
- **Quick access** to individual profiles

### Filtering and Search

- **Search by name** or other attributes
- **Filter by team** or department
- **Filter by role** or status
- **Sort by different criteria**

### Actions Available

- **View Chart**: Switch to the organizational chart view
- **Import CSV**: Bulk import people from a CSV file (admin only)
- **New Person**: Add a new team member (admin only)

## Navigation

### Individual Profiles

Click on any person's name to access their detailed profile, which includes:

- **Personal information** and contact details
- **Team assignments** and reporting relationships
- **Tasks and initiatives** they're involved in
- **Feedback and performance** information
- **Meeting history** and one-on-ones
- **Integration data** from GitHub and Jira

### Chart View

Use the "Chart" button to switch to the organizational hierarchy view, which shows:

- **Reporting relationships** visually
- **Team structure** and hierarchy
- **Interactive navigation** between levels

## Admin Functions

If you're an organization administrator, you have additional capabilities:

### Import People

- **CSV import** for bulk adding team members
- **Template download** with required fields
- **Validation** to ensure data quality

### Add New Person

- **Manual entry** for individual team members
- **Role assignment** and team membership
- **Contact information** and preferences

## Best Practices

### Data Management

- **Keep information current** by regularly updating profiles
- **Use consistent naming** conventions for roles and teams
- **Maintain accurate reporting** relationships

### Organization

- **Use filters effectively** to find specific people quickly
- **Leverage search** for large organizations
- **Regularly review** team composition and structure

### Access Control

- **Respect privacy settings** for sensitive information
- **Use appropriate permissions** for different user roles
- **Maintain data security** across the organization

## Related Topics

- **[People Hierarchy](/help/people-hierarchy)**: Understanding organizational structure
- **[Direct Reports](/help/direct-reports)**: Managing your team members
- **[One-on-Ones](/help/one-on-ones)**: Regular check-ins with team members
- **[Feedback Campaigns](/help/feedback-campaigns)**: Collecting performance feedback

## Tips

- Use the search function to quickly find people in large organizations
- The chart view is helpful for understanding reporting relationships
- Regular updates to people profiles ensure accurate information across the platform
- Leverage filters to focus on specific teams or roles when needed
`,
}
