/**
 * Auto-generated help content: Synopsis Generation
 *
 * This file is automatically generated from feedback-development/synopsis-generation.md.
 * Do not edit this file manually. Instead, edit the markdown file and run:
 *
 *   bun run help:generate
 *
 * Generated on: 2025-12-01T10:53:13.365Z
 */

export interface HelpContent {
  id: string
  title: string
  content: string
  category?: string
}

export const helpContent: HelpContent = {
  id: 'synopsis-generation',
  title: 'Synopsis Generation',
  category: 'Feedback & Development',
  content: `# Synopsis Generation

mpath uses AI‑powered synopsis generation to create concise, professional summaries of a person’s work over a period of time.

Think of a synopsis as a **manager‑ready snapshot** that pulls together tasks, initiatives, GitHub/Jira activity, meetings, and feedback into one narrative.

---

## Overview

### What is a synopsis?

A synopsis is an AI‑generated summary that looks at:

- **Task completion and status changes**
- **Initiative and objective involvement**
- **GitHub pull requests and reviews** (for linked accounts)
- **Jira tickets and project activity**
- **Relevant feedback** and signals

and turns it into **5–8 bullet points** in clear, professional language.

### Why synopses matter (Benefits)

- **Saves time** – no more manual compiling of notes before reviews or check‑ins.
- **Improves consistency** – everyone gets summaries in a similar format.
- **Surfaces patterns** – makes it easier to see themes across weeks or quarters.
- **Anchors discussions in data** – you can talk about impact instead of trying to remember everything.

---

## Where the Data Comes From

Synopses work best when your data in mpath is healthy:

- **Tasks** – status, completion, priority, and initiative links.
- **Initiatives and objectives** – ownership and participation.
- **GitHub** – pull requests, reviews, and merges (for linked accounts).
- **Jira** – tickets, status changes, and project contributions.
- **Feedback** – structured feedback from campaigns, where included.

If a source isn’t connected, that part simply won’t influence the summary.

---

## How to Generate a Synopsis (Step‑by‑Step)

1. Navigate to the **person’s profile** (your own or, for admins, someone else’s).
2. Open the **Synopsis** section.
3. Choose:
   - **Date range** (e.g. last 14, 30, or 90 days).
   - Whether to **include feedback** (when appropriate).
   - Any relevant **focus options** (if available).
4. Trigger **Generate synopsis**.
5. Review the generated summary:
   - Edit lightly if you need to adjust wording.
   - Save it so you can reference it later.

You can keep multiple synopses over time to build a history of contributions.

---

## How to Use Synopses in Practice

### Performance and growth conversations

- Before a review:
  - Generate a synopsis for the last quarter.
  - Combine it with feedback from campaigns and your own notes.
  - Use it as the **starting point** for your written evaluation.

- With the person:
  - Share key points and examples from the synopsis.
  - Discuss where it matches or differs from their self‑assessment.

### Weekly or bi‑weekly manager check‑ins

- Generate shorter‑window synopses (e.g. 14 days) periodically.
- Use them to:
  - Ground \`one-on-ones\` in concrete recent work.
  - Spot load issues and recurring patterns (e.g. always firefighting).

### Initiative and project reporting

- For key initiatives:
  - Use synopses of owners and major contributors to see how work has moved.
  - Pull phrasing or examples into initiative updates.

---

## Privacy, Security, and Access Control

### Who can generate and see synopses

- Individuals can generate and view synopses **only for themselves** (their linked person record).
- Organization **admins** can generate, view, and delete synopses for anyone in their org.

This mirrors the access rules in the application:

- You cannot generate or view synopses for people outside your organization.
- Access is enforced server‑side; it’s not just UI‑based.

### Feedback and sensitive data

- **Private feedback** remains visible only to the author; it is not surfaced to others via synopses.
- Public or shared feedback can be incorporated when you choose to include feedback.

### AI processing

- Only the **minimum necessary data** is sent to the AI service.
- Data is transmitted securely.
- External AI services do not retain your org’s data beyond processing.

---

## Getting the Most from Synopses

### Make your underlying data good

Synopses are only as good as the signals they see:

- Keep **tasks** up‑to‑date (status, completion, initiative links).
- Make sure **GitHub/Jira** accounts are correctly linked.
- Run **feedback campaigns** periodically for richer context.

### Treat synopses as a starting point, not the final word

- Always **review and sanity‑check** what the AI generates.
- Add your own perspective and nuance.
- Use synopses to:
  - Jog your memory.
  - Suggest themes.
  - Provide structure to your write‑ups.

### Communicate clearly with your team

- Explain:
  - What synopses are.
  - What data they use.
  - How they will (and won’t) be used in performance discussions.
- Encourage people to:
  - Read their own synopses.
  - Correct underlying data (tasks, links) if something looks off.

---

## Troubleshooting and Tips

- **Synopsis feels incomplete?**
  - Check that tasks, GitHub, and Jira are linked and up‑to‑date.
  - Try a longer date range.

- **Tone doesn’t match your style?**
  - Edit the text; treat it like a draft.

- **Performance slow for large ranges?**
  - Narrow the date range or temporarily deselect some data sources.

Used thoughtfully, synopses can significantly reduce **manager prep time** while improving the **quality of feedback and discussions** for everyone involved.
`,
}
